font_family JetBrainsMono Nerd Font
font_size 11.0

background_opacity 0.95

# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #ECEFF4
background            #3B4252
selection_foreground  #D8DEE9
selection_background  #434C5E
url_color             #8B5CF6
cursor                #E5E9F0

# black
color0   #E5E9F0
color8   #E5E9F0

# red
color1   #FB7185
color9   #FB7185

# green
color2   #34D399
color10  #34D399

# yellow
color3   #FBBF24
color11  #FBBF24

# blue
color4  #60A5FA
color12 #60A5FA

# magenta
color5   #8B5CF6
color13  #8B5CF6

# cyan
color6   #60A5FA
color14  #60A5FA

# white
color7   #D8DEE9
color15  #E5E9F0
